---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Stack with the following resources:
01 - VPC
02 - Subnets, 01 Publica e 01 Privada
01 - Internet Gateway
01 - NAT Gateway
01 - Instancia EC2, com IP fixo na subnet publica
01 - Instancia EC2, com IP dinamico na subnet privada
01 - Grupo de Segurança para acesso SSH em todas as instancias criadas por este grupo
'
Parameters:
   ManagementKeyPair:
      Description: Indicar a chave SSH para gerencia dos servidores
      Type: "AWS::EC2::KeyPair::KeyName"
   
Resources:

#VPC Creation

   GhostTestVPC:
      Type: "AWS::EC2::VPC"
      Properties:
         CidrBlock: 10.0.0.0/16
         InstanceTenancy: default


# Internet gateways (ipv4, and egress for ipv6)

   InternetGateway:
      Type: "AWS::EC2::InternetGateway"
      

   InternetGatewayAttachment:
      Type: "AWS::EC2::VPCGatewayAttachment"
      Properties:
         VpcId: !Ref GhostTestVPC
         InternetGatewayId: !Ref InternetGateway
         
   EgressOnlyInternetGateway:
      Type: "AWS::EC2::EgressOnlyInternetGateway"
      Properties:
         VpcId: !Ref GhostTestVPC        
         